### ISSUE TITLE
Error on OpenAPI v3.0.3 file

### ISSUE THREAD

**Issue by amacfie** [sennder/python-client-generator#20]
The file [openapi.json](https://github.com/sennder/python-client-generator/files/14649468/openapi.json) comes from https://editor.swagger.io/ as an example OpenAPI schema.

Running `python -m python_client_generator --open-api openapi.json --package-name foo_bar --project-name foo-bar --outdir clients` gives
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/tmp/.venv/lib/python3.11/site-packages/python_client_generator/__main__.py", line 4, in <module>
    main()
  File "/tmp/.venv/lib/python3.11/site-packages/python_client_generator/main.py", line 48, in main
    generate_models(dereferenced_swagger, package_path / "models.py")
  File "/tmp/.venv/lib/python3.11/site-packages/python_client_generator/generate_models.py", line 199, in generate_models
    models = get_models(schemas)
             ^^^^^^^^^^^^^^^^^^^
  File "/tmp/.venv/lib/python3.11/site-packages/python_client_generator/generate_models.py", line 146, in get_models
    p["refs"] = get_references(o)
                ^^^^^^^^^^^^^^^^^
  File "/tmp/.venv/lib/python3.11/site-packages/python_client_generator/generate_models.py", line 69, in get_references
    refs += _get_schema_references(p_schema)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/.venv/lib/python3.11/site-packages/python_client_generator/generate_models.py", line 51, in _get_schema_references
    return [schema["title"]]
            ~~~~~~^^^^^^^^^
KeyError: 'title'
```

**Comment by nj-senn** [comment]
Hi @amacfie, thank you for reporting the issue, I have a PR ready for review, once its approved we will merge it to fix this issue, in the meanwhile you can have a look at the code comments to understand what is the root cause and update your OpenAPI JSON file accordingly until we release the fix.
